### ISSUE TITLE
Creating a telegram bot for this project

### ISSUE THREAD

**Issue by diveshuttam** [Ishan-sopho/SSMS_daily_mess_menu#1]
creating a [telegram bot](https://core.telegram.org/bots) for this can be a really nice feature.

**Comment by twitu** [comment]
what purpose would the telegram bot serve ? And can you point me towards some examples of projects using telegram bot ?

**Comment by diveshuttam** [comment]
you can basically use it similar to dc++ menu commands. from the bot you can serve the users menu on telegram. Though main telegram  bot home page is linked in initial comment. some samples linked [here](https://core.telegram.org/bots/samples) . It could be made another project extending to this one.

**Comment by twitu** [comment]
Can work on it.

**Comment by twitu** [comment]
created new branch for [Telegram Bot](https://github.com/Ishan-sopho/SSMS_daily_mess_menu/tree/Telegram_bot)

**Comment by diveshuttam** [comment]
prototype version created at https://github.com/diveshuttam/MessMenuBot
